version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      pip-dependencies:
        patterns:
          - "*" # All dependabot updates are grouped
